### PR TITLE
Added support for grammar inside of  <mj-style />

### PR DESCRIPTION
**Pull request by matteobertoldo**
Added the default highlight css style for `<mj-style>` tag.

### CODE REVIEW

**Comment by matteobertoldo** [comment]
@iRyusa @ngarnier Any updated about this PR?

**Comment by ngarnier** [comment]
Very sorry @matteobertoldo, I think we totally missed your PR. Can you check @kmcb777?

**Comment by matteobertoldo** [comment]
@kmcb777 Any updated? Please considering is a good enanchement for highlight the all `css` code into `<mj-style />` tag!

**Comment by iRyusa** [comment]
I'll try to setup an env with your patch monday to merge & deploy, sorry about this big delay :(

**Comment by matteobertoldo** [comment]
@iRyusa no problem, thank u so much for considering this.

**Comment by iRyusa** [comment]
Everything looks fine ! I'll try to publish it asap

**Pull request merged**
