### PR TITLE
Add missing mjml snippets 

### PR DESCRIPTION
**Pull request by arthurkatz**
I've simply added the missing snippets.

### CODE REVIEW

**Comment by ngarnier** [comment]
Hey @arthurkatz, so sorry for the late answer, we missed this PR. 

Anyway, THANKS a lot for your contribution! It seems good to be merged but I have one question, shouldn't this file be updated too? https://github.com/mjmlio/language-mjml/blob/master/settings/language-mjml.cson

**Comment by arthurkatz** [comment]
Hey @ngarnier, 
you're right ! I correct this push it today ;)

**Comment by ngarnier** [comment]
Awesome, thanks :-). So I guess you don't use a local version of the package with those changes?

**Comment by ngarnier** [comment]
@arthurkatz hey Arthur, have you had time to make the change?

**Comment by arthurkatz** [comment]
@ngarnier Done ;)

**Comment by ngarnier** [comment]
Very sweet, seems good to me, thanks for your contribution @arthurkatz!

**Pull request merged**
